---
title: "viz3"
author: "Sarahy Martinez"
date: "2024-10-03"
output: github_document
---

```{r setup, include=FALSE}

library(tidyverse)

knitr:: opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal()+ theme(legend.position = "bottom"))

options(
  
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_fill_discrete = scale_fill_viridis_d()    

scale_colour_discrete = scale_fill_viridis_d() 

```


## Load the weather data

```{r}

weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") %>% 
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%   #extract the month variable, lubridate package tidyverse adjacent says to get the floor of a date aned sort of round whatever date or pull the dates donwn to the nearest. month is rounded down
  select(name, id, everything())


weather_df

```


## ` group_by`

```{r}
weather_df %>% 
  group_by(name) #appears like nothing happened by whats different says groups name[3]



weather_df %>% 
  group_by(name, month) %>% #groups by name and month
  ungroup() #gets rid of whatever grouping structure you have 



```


## counting the things

ie. how many ovbservations exist 
count months in this code 

```{r}

weather_df %>% 
  group_by(month) %>% 
  summarize(n_obs = n())   #n() counts for you, n_obs is the variable you created and end result is a tibble 



```



we can also use count()


```{r}

weather_df %>% 
  count(month, name = "n_obs")
```

**NEVER** use base R's `table` 


```{r, eval =FALSE}
  weather_df %>% 
  pull(month) %>% 
  table()  #painful to look at because the result isnt a dataframe, to get to the table function 
```



other helpful counters 

```{r}
weather_df %>% 
  group_by(month) %>% 
  summarize(
    n_obs = n(),
    n_days = n_distinct(date) #n_distint looks at this month how many dated are distinct 
  )

```









