---
title: "Visualization"
subtitle: "Part II"
author: "Sarahy Martinez"
date: "2024-10-03"
output: github_document
---

## Look at the weather data 


```{r}
library(tidyverse)
library(patchwork)

```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())


```

## Remember this plot?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)  #3 aesthetics defined  tmin, tmax, color 

```

If this were a plot we wanted to share its sufficient but someone might not know whats going on so we will add a text or label.

## Labels 

```{r}

weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5)+
  labs(
    title = "Temperature Plot",
    x = "Minimum Daily Temperature (C)",
    y = "Maximum Daily Temperature (C)",
    caption = " Data from the rnoaa package; temperatures in 2017"
  )
```

































